<?xml version="1.0"?>
<package format="3">
  <name>dcaron_interfaces</name>
  <version>0.2.0</version>
  <description>DFLink relative-motion action interface.</description>
  <maintainer email="220290149+yangzkee@users.noreply.github.com">yangzkee</maintainer>
  <license>Proprietary</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <depend>geometry_msgs</depend>
  <member_of_group>rosidl_interface_packages</member_of_group>
  <export><build_type>ament_cmake</build_type></export>
</package>
